version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: smoke_bot_postgres
    volumes:
      - smoke_bot_db:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    networks:
      - smoke_bot

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: smoke_bot_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:80"
    depends_on:
      - db
    networks:
      - smoke_bot

networks:
  smoke_bot:
    driver: bridge

volumes:
  smoke_bot_db:
